# raise - lançando exceções (erros)
# https://docs.python.org/pt-br/3/library/exceptions.html#built-in-exceptions

print(123)

raise ValueError('Deu erro')

print(456)
